<script lang="ts">
	import Eyes from '$components/Eyes';
	import DecorativeText from '$components/DecorativeText.svelte';
</script>

<section id="hero">
	<div class="circle" />
	<div class="content">
		<img src="avatar.png" alt="Thomas Gouveia Lopes smiling" />
		<div class="text">
			<h1>Hi!</h1>
			<p>
				<span>My name is</span>
				<DecorativeText>Thomas</DecorativeText>
				<span class="dot">.</span>
			</p>
		</div>
	</div>
	<div class="bottom">
		<!-- Generated by circletype: https://circletype.labwire.ca/ -->
		<div id="circle-type">
			<div aria-label="check out my work" style="position: relative; height: 3.40369em;">
				<span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.288021em) rotate(-57.7281deg); transform-origin: center 5.625em 0px;"
					>c</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.343056em) rotate(-49.9101deg); transform-origin: center 5.625em 0px;"
					>h</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.310938em) rotate(-41.8083deg); transform-origin: center 5.625em 0px;"
					>e</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.288021em) rotate(-34.3882deg); transform-origin: center 5.625em 0px;"
					>c</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.318056em) rotate(-26.88deg); transform-origin: center 5.625em 0px;"
					>k</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.138021em) rotate(-21.23deg); transform-origin: center 5.625em 0px;"
					>&nbsp;</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.322569em) rotate(-15.5241deg); transform-origin: center 5.625em 0px;"
					>o</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.340451em) rotate(-7.31037deg); transform-origin: center 5.625em 0px;"
					>u</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.211979em) rotate(-0.466711deg); transform-origin: center 5.625em 0px;"
					>t</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.138021em) rotate(3.86919deg); transform-origin: center 5.625em 0px;"
					>&nbsp;</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.521528em) rotate(12.0399deg); transform-origin: center 5.625em 0px;"
					>m</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.289063em) rotate(22.0817deg); transform-origin: center 5.625em 0px;"
					>y</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.138021em) rotate(27.3725deg); transform-origin: center 5.625em 0px;"
					>&nbsp;</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.452083em) rotate(34.6829deg); transform-origin: center 5.625em 0px;"
					>w</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.32257em) rotate(44.2795deg); transform-origin: center 5.625em 0px;"
					>o</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.207465em) rotate(50.8457deg); transform-origin: center 5.625em 0px;"
					>r</span
				><span
					style="position: absolute; bottom: auto; left: 50%; transform: translateX(-0.318056em) rotate(57.356deg); transform-origin: center 5.625em 0px;"
					>k</span
				>
			</div>
		</div>
		<div class="eyes">
			<Eyes />
		</div>
	</div>
</section>

<style lang="postcss">
	@keyframes expand {
		0% {
			margin-left: 0rem;
			padding-right: 0rem;
			max-width: 0;
		}
		100% {
			margin-left: var(--expand-ml, 0);
			padding-right: 1rem;
			max-width: var(--expand-max-w, 0);
		}
	}

	@keyframes fade-top-to-bottom {
		0% {
			opacity: 0;
			transform: translateY(-1rem);
		}
		100% {
			opacity: 1;
			transform: translateY(0);
		}
	}

	@keyframes fade-in {
		0% {
			opacity: 0;
		}
		100% {
			opacity: 1;
		}
	}

	@keyframes scale {
		0% {
			transform: scale(0);
		}
		100% {
			transform: scale(1);
		}
	}

	#hero {
		height: 100vh;
		min-height: 650px;
		max-height: 1440px;
		position: relative;
		overflow: hidden;

		@media (--bp-md) {
			display: grid;
			place-items: center;
			min-height: 800px;
		}
	}

	.circle {
		position: absolute;
		top: -350px;
		right: -400px;

		--size: 600px;
		width: var(--size);
		height: var(--size);

		background: var(--fiery-rose);
		opacity: 0.25;
		border-radius: 50%;
		animation: scale 1000ms 0ms ease both;
		z-index: var(--z-index-1);

		@media (--bp-md) {
			animation-delay: 2000ms;
			animation-duration: 1000ms;
		}

		@media (--bp-lg) {
			animation-delay: 1250ms;
			animation-duration: 1000ms;
			top: -320px;
			right: -250px;
		}
	}

	.content {
		display: flex;
		flex-direction: column;
		justify-content: flex-start;
		align-items: center;
		margin-top: 64px;

		position: relative;
		z-index: var(--z-index-2);

		@media (--bp-md) {
			margin-top: 0;
			flex-direction: row;
		}

		img {
			--size: 256px;
			width: var(--size);
			height: var(--size);

			animation: fade-in 250ms 100ms ease both;

			@media (--bp-lg) {
				--size: 320px;
			}
		}

		.text {
			font-family: var(--ff-display);
			overflow: hidden;
			white-space: nowrap;
			text-align: center;

			@media (--bp-md) {
				text-align: left;
				margin-left: 2rem;
				padding-right: 1rem;
			}

			@media (--bp-lg) {
				margin-left: 4rem;
			}

			h1 {
				font-size: 4.5rem;
				font-weight: 700;
				line-height: 6rem;

				animation: fade-in 250ms 100ms ease both;

				@media (--bp-lg) {
					font-size: 6rem;
					line-height: 9rem;
				}
			}

			p:nth-child(2) {
				font-size: 2rem;
				line-height: 3.5rem;
				font-weight: 600;
				margin-top: -1rem;

				animation: fade-in 250ms 100ms ease both;

				@media (--bp-lg) {
					font-size: 3rem;
					line-height: 4.5rem;
				}
			}
		}
	}

	.bottom {
		display: flex;
		flex-direction: column;
		align-items: center;

		position: absolute;
		left: 50%;
		bottom: 0rem;
		transform: translateX(-50%);

		padding-bottom: 1rem;

		animation: fade-in 1000ms ease 1000ms both;

		@media (--bp-md) {
			animation-delay: 2000ms;
		}

		@media (--bp-lg) {
			animation-delay: 1500ms;
		}

		#circle-type {
			font-family: var(--ff-display);
			font-size: 2rem;
			font-weight: 600;
			opacity: 0.25;

			@media (--bp-lg) {
				font-size: 3rem;
			}
		}

		.eyes {
			margin-top: -2.5rem;

			@media (--bp-lg) {
				margin-top: -3rem;
			}
		}
	}

	.dot {
		margin-left: -0.5rem;
	}
</style>
